services:

# HERE COMES THE DATABASE SERVICE WE WANT TO SET UP
  db:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: 'mydatabase'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
      ## DISABLED FOR THIS TEST!
    # volumes:
      # - my-db:/var/lib/mysql
# Names our volume
# DISABLED FOR THIS TEST!
# volumes:
#  my-db:

# HERE COMES THE JAVA APP SERVICE WE WANT TO SET UP

  app:
  # instead of using an image we build a new one from the Dockerfile
    build: .
    restart: on-failure
    container_name: java-app
    ports:
      - "8080:8080"
    expose:
      - '8080'      
    depends_on:
            - db

            